from typing import Protocol

from src.domain.agent import Agent
from src.domain.entry import Entry
from src.domain.ids import AgentId, SessionId
from src.domain.session import Session
from src.domain.user import User


class UserRepo(Protocol):
    async def get_by_api_key_hash(self, key_hash: str) -> User | None: ...


class SessionRepo(Protocol):
    async def create(self, session: Session) -> Session: ...
    async def get(self, session_id: SessionId) -> Session | None: ...


class AgentRepo(Protocol):
    async def create(self, agent: Agent) -> Agent: ...
    async def get(self, agent_id: AgentId) -> Agent | None: ...
    async def update(self, agent: Agent) -> Agent: ...


class EntryRepo(Protocol):
    async def create(self, entry: Entry) -> Entry: ...
    async def list_by_agent(self, agent_id: AgentId) -> list[Entry]: ...
    async def next_sequence(self, agent_id: AgentId) -> int: ...
